/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Comentarios: () => import('#controllers/comentarios_controller'),
  Curtidas: () => import('#controllers/curtidas_controller'),
  Feeds: () => import('#controllers/feeds_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Postagens: () => import('#controllers/postagens_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Seguidores: () => import('#controllers/seguidores_controller'),
  Usuarios: () => import('#controllers/usuarios_controller'),
}
