/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ComentarioSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postagemId', 'texto', 'updatedAt', 'userId'] as const
  $columns = ComentarioSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postagemId: number | null
  @column()
  declare texto: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class CurtidaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postagemId', 'updatedAt', 'userId'] as const
  $columns = CurtidaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postagemId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class PostagenSchema extends BaseModel {
  static $columns = ['createdAt', 'fotoUrl', 'id', 'legenda', 'updatedAt', 'userId'] as const
  $columns = PostagenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fotoUrl: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare legenda: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SeguidoreSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'seguidoId', 'seguidorId', 'updatedAt'] as const
  $columns = SeguidoreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare seguidoId: number | null
  @column()
  declare seguidorId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['biografia', 'createdAt', 'email', 'fotoUrl', 'id', 'isAtivo', 'nomeCompleto', 'senha', 'updatedAt', 'usuario'] as const
  $columns = UserSchema.$columns
  @column()
  declare biografia: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fotoUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAtivo: boolean | null
  @column()
  declare nomeCompleto: string
  @column()
  declare senha: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usuario: string
}
